name: RegelnUI
author: Ameer4Real
main: Ameer4Real\InfoUI
version: 0.1
description: sehe server regeln in UI Form!
api: [3.0.0]
commands:
    regeln:
        default: true
        description: ยง4RegelnUI
