---
#Here you can change the messages that will display
#Use "§" as a color symbol
#Use "\n" to go to the next line
#The title of the menu
Title: "§4§lRegelnUI"
#The content of the menu (Description)
Content: "§l§4 YT : Crow Balde(Inhaber Kanal) \n§6 YT : Caostaylor(Administrator Kanal)"
#Returns button name
Button: "§a§lApteztieren"
...
