---
#Here you can change the messages that will display
#Use "§" as a color symbol
#Use "\n" to go to the next line
#The title of the menu
Title: "§a§lInfo§bUI"
#The content of the menu (Description)
Content: "§bWelcome auf denn §e§oServer§r§7! \n §4Vergiss Nicht auf YT zu Abonieren \n §2YT : Crow Balde \n §bVergiss Nicht Denn Discord Server \n §4Discord : bit.ly/DCPaincraft \n §6Wir Versuche Devoloper Zu Bekommen"
#Returns button name
Button: "§aApteztieren"
...
